import { useState } from 'react';

export const FAQSection = () => {
    const [activeQuestion, setActiveQuestion] = useState(null);

    const questionsAndAnswers = [
        {
            question: 'What is Bitelinkz?',
            answer: 'Bitelinkz is a URL shortening service that allows you to create concise and branded links, track their performance, and simplify your online sharing experience.',
        },
        {
            question: 'How do I create a short link?',
            answer: 'To create a short link, use our URL shortening form on the homepage. Enter your long URL, and Bitelinkz will generate a short link for you.',
        },
        {
            question: 'Is Bitelinkz free to use?',
            answer: 'Yes, Bitelinkz is free to use. We also offer premium features for users who want additional capabilities.',
        },
        {
            question: 'Can I track the performance of my links?',
            answer: 'Yes, Bitelinkz provides detailed analytics to track the performance of your links, including click-through rates, geographic location of users, and more.',
        },
        {
            question: 'How secure are the shortened links?',
            answer: 'We prioritize the security of your links. All links generated by Bitelinkz are private, and we take measures to prevent unauthorized access.',
        },
        {
            question: 'Is there a mobile app for Bitelinkz?',
            answer: 'Currently, Bitelinkz is available as a web application. However, we are working on developing a mobile app for a better user experience on smartphones.',
        },
    ];

    const handleQuestionClick = (index) => {
        setActiveQuestion(activeQuestion === index ? null : index);
    };

    return (
        <div className='max-w-screen mx-auto mt-8 flex flex-wrap justify-center align-center'>
            <h3 className='text-3xl font-semibold mb-4'>Frequently Asked Questions</h3>
            <div className='flex flex-wrap w-full '>
                <div className='w-full md:w-1/2 space-y-4 p-2'>
                    {questionsAndAnswers.slice(0, 3).map((qa, index) => (
                        <div key={index} onClick={() => handleQuestionClick(index)} className='cursor-pointer'>
                            <div className='flex items-center justify-between border p-4 rounded-md'>
                                <div className='flex-1'>
                                    <h6 className='text-xl font-semibold'>{qa.question}</h6>
                                </div>
                                <div className='ml-2'>{activeQuestion === index ? '-' : '+'}</div>
                            </div>
                            {activeQuestion === index && (
                                <div className='shadow-md p-4 rounded-md'>
                                    <p>{qa.answer}</p>
                                </div>
                            )}
                        </div>
                    ))}
                </div>
                <div className='w-full md:w-1/2 space-y-4 p-2'>
                    {questionsAndAnswers.slice(3).map((qa, index) => (
                        <div key={index + 3} onClick={() => handleQuestionClick(index + 3)} className='cursor-pointer'>
                            <div className='flex items-center justify-between border p-4 rounded-md'>
                                <div className='flex-1'>
                                    <h6 className='text-xl font-semibold'>{qa.question}</h6>
                                </div>
                                <div className='ml-2'>{activeQuestion === index + 3 ? '-' : '+'}</div>
                            </div>
                            {activeQuestion === index + 3 && (
                                <div className='shadow-md p-4 rounded-md'>
                                    <p>{qa.answer}</p>
                                </div>
                            )}
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
};
